server:
  port: 10754
project:
  version: "0.0.1"
spring:
  application:
    name: "delivery"
  data:
    mongodb:
      database: "micropos"
      host: "localhost"
      port: 10500
  cloud:
    nacos.discovery.server-addr: "http://localhost:10400"
    function:
      definition: makeDelivery
    stream:
      function:
        bindings:
          makeDelivery-in-0: deliver
      rabbit:
        bindings:
          deliver:
            destination: deliver
            consumer:
              declare-exchange: false  